DASH_APP:
  APP_TITLE: GeoPROD
  UPDATE_TITLE: Updating...
  DEBUG: False

DASH_THEME:
  THEME: COSMO

TEMPLATE:
  LOGO_SOURCE: 
  WATERMARK_SOURCE: 
  SHOW_LEGEND_INSIDE: False
  SHOW_RANGESELECTOR: False

VERSION: v-1.0.0
GITHUB_LINK: https://github.com/Alex1um/Geo
GITHUB_REPO: Alex1um/Geo
